[FEAT] Update bin/*, .zsh configs and, .vimrc

diff --git a/bin/code_merge_sh b/bin/code_merge_sh
--- a/bin/code_merge_sh
+++ b/bin/code_merge_sh
@@ -1,10 +1,13 @@
 #!/u/chehuang/bin/bash
 
 if [[ -n "$VSCODE_IPC_HOOK_CLI" ]]; then
-	REMOTE_CLI="$(which -a code | rg /remote-cli/)"
-	if [[ -n "$REMOTE_CLI" ]]; then
-		"$REMOTE_CLI" --wait -m "$3" "$2" "$1" "$4"
-		exit $?
-	fi
+    REMOTE_CLI="$(which -a code | rg /remote-cli/)"
+    if [[ -n "$REMOTE_CLI" ]]; then
+        "$REMOTE_CLI" --wait -m "$3" "$2" "$1" "$4"
+        exit $?
+    fi
+else
+    echo "Missing VSCODE_IPC_HOOK_CLI" >&2
+    exit 1
 fi
 
diff --git a/bin/get_x_display_sh b/bin/get_x_display_sh
--- a/bin/get_x_display_sh
+++ b/bin/get_x_display_sh
@@ -4,12 +4,12 @@ help="Usage: get_x_display_sh [<OPTION>...] <X_SERVER>
 options:
     -u, --user <USER>   Specify another user instead of current user
     -e, --env <ENV>     Specify another env instead of 'DISPLAY'
-    -v, --verbose		Show verbose messages in console
-    -h, --help			Display this help and exit
+    -v, --verbose       Show verbose messages in console
+    -h, --help          Display this help and exit
 "
 
-# shellcheck source-path=SCRIPTDIR
-source "utils_sh"
+source "/u/chehuang/bin/utils_src"
+PATH=/u/chehuang/bin:$PATH
 
 xserver_name=""
 user_name="$(whoami)"
@@ -36,13 +36,13 @@ while [[ $# -gt 0 ]]; do
             if [[ -z "$xserver_name" ]]; then
                 xserver_name="$1"; shift
             else
-                echo "Error: Can't accept multiple server" >&2
+                utils::ERROR "Can't accept multiple server\n" >&2
                 exit 1
             fi
     esac
 done
 
-utils::verbose --msg-color "${CYAN}" "xserver=$xserver_name; user=$user_name; env=$env_name" >&2
+utils::verbose -c "${CYAN}" "xserver=$xserver_name; user=$user_name; env=$env_name\n" >&2
 
 # End if not a ssh connection
 [[ -z "$SSH_CLIENT" ]] && { echo "$DISPLAY"; exit 0; }
@@ -66,9 +66,11 @@ if [[ "$server_ip" == "$xserver_ip" ]]; then
 fi
 [[ "$client_ip" == "$xserver_ip" ]] && { echo "$DISPLAY"; exit 0; }
 
-tty="$(w --no-header | awk '{print $1,$2,$3}' | rg "$user_name" | rg -m 1 "$xserver_name" | awk '{print $2}')"
+tty="$(w --no-header | awk '{print $1,$2,$3}' | rg "$user_name" | rg -m 1 "$xserver_name" | \
+    awk '{print $2}')"
 if [[ -z "$tty" && "$xserver_name" != "$xserver_ip" ]]; then
-    tty="$(w --no-header | awk '{print $1,$2,$3}' | rg "$user_name" | rg -m 1 "$xserver_ip" | awk '{print $2}')"
+    tty="$(w --no-header | awk '{print $1,$2,$3}' | rg "$user_name" | rg -m 1 "$xserver_ip" | \
+        awk '{print $2}')"
 fi
 
 if [[ -n "$tty" ]]; then
@@ -78,8 +80,10 @@ if [[ -n "$tty" ]]; then
     echo "${display#"${env_name}"=}"
     exit 0
 else
-    echo "${BASH_SOURCE[*]}:${LINENO}" >&2
-    echo "  Error: Can't find your tty on $(hostname) which connect from $xserver_name, please connect to $(hostname) from $xserver_name with ssh X11 forwarding first" >&2
+    utils::verbose -f -c "${BGREEN}" -p "* " "${BASH_SOURCE[*]}:${LINENO}\n" >&2
+    utils::ERROR -p "  Error" \
+        "Can't find your tty on $(hostname) which connect from $xserver_name, please " \
+        "connect to $(hostname) from $xserver_name with ssh X11 forwarding first\n" >&2
     exit 1
 fi
 
diff --git a/bin/lsf_sh b/bin/lsf_sh
--- a/bin/lsf_sh
+++ b/bin/lsf_sh
@@ -19,7 +19,7 @@ sub-commands:
         example: lsf_sh jobs edag_batch1 batch_cme
     kill
         Kill jobs in specific app
-        usage: lsf_sh kill [<OPTION>...] [<MODULE>] [<JOB-ID>]
+        usage: lsf_sh kill [<OPTION>...] [<JOB-ID>]
         example: lsf_sh kill edag_int 1234567  # Without interactive-kill, both module and job-id are needed
         example: lsf_sh kill -i  # Search in all possible modules, might be slow
         example: lsf_sh kill -i edag_int  # Only search in specific module
@@ -60,7 +60,7 @@ sub-commands:
             -P, --preset <ENUM>             Use preset enums. They are order irrelevant, and any explicit declared
                                             params will override params in preset.
                                             B(batch)='-m edag_batch1 -o \"-app batch_cme -R \\\"select[os=AlmaLinux8.4]\\\" -R \\\"rusage[mem=32G]\\\" -P <tag> -We 10:0\"'
-                                            I(integrate)='-m edag_int -o \"-app int_cme -R \\\"select[os=AlmaLinux8.4]\\\" -R \\\"rusage[mem=32G]\\\" -P <tag> -We 240:0\"'
+                                            I(integrate)='-m edag_int -o \"-app int_cme -R \\\"select[os=AlmaLinux8.4]\\\" -R \\\"rusage[mem=32G]\\\" -P <tag> -We 720:0\"'
                                             <tag>=\"harness=sysreg:#:product=primewave:#:project=primewave:#:identifier=\$(whoami)_\$(date +\"%Y-%m-%d_%H:%M:%S\")\"
                                             E.G. 'lsf_sh -We 1:0 -P B -m edag_batch2' ===
                                                  'lsf_sh -m edag_batch2 -o \"-app batch_cme -R \\\"select[os=AlmaLinux8.4]\\\" -R \\\"rusage[mem=32G]\\\" -P <tag> -We 1:0'
@@ -79,8 +79,8 @@ MODULES=(
     #"edag_shared"
 )
 
-# shellcheck source-path=SCRIPTDIR
-source "utils_sh"
+source "/u/chehuang/bin/utils_src"
+PATH=/u/chehuang/bin:$PATH
 
 [[ $# -le 0 ]] && echo "$help" && exit 0
 
@@ -98,6 +98,29 @@ interactive_kill=false
 dry_run=false
 verbose=false
 
+# Handle partial sub-command
+case $sub_command in
+    modules|m|mo|mod|modu|modul|module)
+        sub_command="modules"
+        ;;
+    jobs|j|jo|job)
+        sub_command="jobs"
+        ;;
+    kill|k|ki|kil)
+        sub_command="kill"
+        ;;
+    hist|h|hi|his)
+        sub_command="hist"
+        ;;
+    sub|s|su)
+        sub_command="sub"
+        ;;
+    attach|a|at|att|atta|attac)
+        sub_command="attach"
+        ;;
+esac
+
+
 # Arguments processing start
 shift
 case $sub_command in
@@ -114,13 +137,16 @@ case $sub_command in
                     verbose=true
                     ;;
                 *)
-                    [[ -n "$module" ]] && { echo "Error: Command 'modules' do not accept multiple modules" && exit 1; }
+                    if [[ -n "$module" ]]; then
+                        utils::ERROR "Command 'modules' does not accept multiple modules\n" >&2
+                        exit 1
+                    fi
                     module="$1"
                     ;;
             esac
             shift
         done
-        utils::verbose --msg-color "${CYAN}" "sub_command=modules; MODULE=$module" >&2
+        utils::verbose -c "${CYAN}" "sub_command=modules; MODULE=$module\n"
         ;;
     jobs)
         while [[ $# -gt 0 ]]; do
@@ -133,7 +159,11 @@ case $sub_command in
                     ;;
                 *)
                     if [[ -n "$module" ]]; then
-                        [[ -n "$app" ]] && { echo "Error: Command 'jobs' do not accept multiple modules or apps" && exit 1; }
+                        if [[ -n "$app" ]]; then
+                            utils::ERROR "Command 'jobs' do not accept multiple modules or" \
+                                "apps\n" >&2
+                            exit 1
+                        fi
                         app="$1"
                     else
                         module="$1"
@@ -142,8 +172,8 @@ case $sub_command in
             esac
             shift
         done
-        [[ -z "$module" ]] && { echo "Error: Missing module" && exit 1; }
-        utils::verbose --msg-color "${CYAN}" "sub_command=jobs; MODULE=$module; APP=$app" >&2
+        [[ -z "$module" ]] && { utils::ERROR "Missing module\n" >&2 && exit 1; }
+        utils::verbose -c "${CYAN}" "sub_command=jobs; MODULE=$module; APP=$app\n"
         ;;
     kill)
         while [[ $# -gt 0 ]]; do
@@ -161,17 +191,21 @@ case $sub_command in
                     verbose=true
                     ;;
                 *)
-                    [[ -n "$job_id" ]] && { echo "Error: Command 'jobs' do not accept multiple job-ids" && exit 1; }
+                    if [[ -n "$job_id" ]]; then
+                        utils::ERROR "Command 'jobs' do not accept multiple job-ids\n" >&2
+                        exit 1
+                    fi
                     job_id="$1"
                     ;;
             esac
             shift
         done
         if [[ "$interactive_kill" == false ]]; then
-            [[ -z "$module" ]] && { echo "Error: Missing module" && exit 1; }
-            [[ -z "$job_id" ]] && { echo "Error: Missing job-id" && exit 1; }
+            [[ -z "$module" ]] && { utils::ERROR "Missing module\n" >&2 && exit 1; }
+            [[ -z "$job_id" ]] && { utils::ERROR "Missing job-id\n" >&2 && exit 1; }
         fi
-        utils::verbose --msg-color "${CYAN}" "sub_command=kill; MODULE=$module; APP=$app; JOB-ID=$job_id; interactive-kill=$interactive_kill" >&2
+        utils::verbose -c "${CYAN}" "sub_command=kill; MODULE=$module; APP=$app;" \
+            "JOB-ID=$job_id; interactive-kill=$interactive_kill\n"
         ;;
     hist)
         while [[ $# -gt 0 ]]; do
@@ -205,7 +239,11 @@ case $sub_command in
                     ;;
                 *)
                     if [[ -n "$module" ]]; then
-                        [[ -n "$app" ]] && { echo "Error: Command 'jobs' do not accept multiple modules or apps" && exit 1; }
+                        if [[ -n "$app" ]]; then
+                            utils::ERROR "Command 'jobs' do not accept multiple modules or" \
+                                "apps\n" >&2
+                            exit 1
+                        fi
                         app="$1"
                     else
                         module="$1"
@@ -214,8 +252,11 @@ case $sub_command in
             esac
             shift
         done
-        [[ -z "$module" ]] && { echo "Error: Missing module" && exit 1; }
-        utils::verbose --msg-color "${CYAN}" "sub_command=hist; MODULE=$module; APP=$app; long=${hist_args[0]}; all=${hist_args[1]}; pending=${hist_args[2]}; running=${hist_args[3]}; suspend=${hist_args[4]}; done=${hist_args[5]}; job-id=$job_id" >&2
+        [[ -z "$module" ]] && { utils::ERROR "Missing module\n" >&2 && exit 1; }
+        utils::verbose -c "${CYAN}" "sub_command=hist; MODULE=$module; APP=$app;" \
+            "long=${hist_args[0]}; all=${hist_args[1]}; pending=${hist_args[2]}; " \
+            "running=${hist_args[3]}; suspend=${hist_args[4]}; done=${hist_args[5]}; " \
+            "job-id=$job_id\n"
         ;;
     sub)
         _sub_preset=""
@@ -231,20 +272,24 @@ case $sub_command in
             esac
         done
 
-        _tag="\"harness=sysreg:#:product=primewave:#:project=primewave:#:identifier=\$(whoami)_\$(date +\"%Y-%m-%d_%H:%M:%S\")\""
+        _tag_part1="harness=sysreg:#:product=primewave:#:project=primewave:#:"
+        _tag_part2="identifier=\$(whoami)_\$(date +\"%Y-%m-%d_%H:%M:%S\")"
+        _tag="\"${_tag_part1}${_tag_part2}\""
         while read -rn 1 ch; do
             case $ch in
                 B|b)
                     module="edag_batch1"
-                    sub_options="-app batch_cme -R \"select[os=AlmaLinux8.4]\" -R \"rusage[mem=32G]\" -P $_tag -We 10:0"
+                    sub_options="-app batch_cme -R \"select[os=AlmaLinux8.4]\" " \
+                        "-R \"rusage[mem=32G]\" -P $_tag -We 10:0"
                     ;;
                 I|i)
                     module="edag_int"
-                    sub_options="-app int_cme -R \"select[os=AlmaLinux8.4]\" -R \"rusage[mem=32G]\" -P $_tag -We 240:0 -Is csh"
+                    sub_options="-app int_cme -R \"select[os=AlmaLinux8.4]\" "
+                    sub_options+="-R \"rusage[mem=16G]\" -P $_tag -We 720:0 -Is csh"
                     ;;
             esac
         done < <(echo -n "$_sub_preset")
- 
+
         set -- "${_sub_args[@]}"
         while [[ $# -gt 0 ]]; do
             case $1 in
@@ -266,11 +311,18 @@ case $sub_command in
             esac
             shift
         done
-        [[ -z "$module" ]] && { echo "Error: Missing module to load" && exit 1; }
-        [[ "$sub_options" == *"-Is "* ]] && { __tmp="${sub_options##*-Is }"; interactive_shell="${__tmp%%( *|$)}"; }
-        [[ -z "$interactive_shell" && -z "$command" ]] && { echo "Error: Missing command to execute" && exit 1; }
+        [[ -z "$module" ]] && { utils::ERROR "Missing module to load\n" >&2 && exit 1; }
+        if [[ "$sub_options" == *"-Is "* ]]; then
+            __tmp="${sub_options##*-Is }"
+            interactive_shell="${__tmp%%( *|$)}"
+        fi
+        if [[ -z "$interactive_shell" && -z "$command" ]]; then
+            utils::ERROR "Missing command to execute\n" >&2
+            exit 1
+        fi
 
-        utils::verbose --msg-color "${CYAN}" "sub_command=sub; module=$module; sub-options=$sub_options; COMMAND=$command" >&2
+        utils::verbose -c "${CYAN}" "sub_command=sub; module=$module;" \
+            "sub-options=$sub_options; COMMAND=$command\n"
         ;;
     attach)
         module="edag_int"
@@ -283,16 +335,17 @@ case $sub_command in
                     verbose=true
                     ;;
                 *)
-                    echo "Error: Invalid parameters for command 'attach'"
+                    utils::ERROR "Invalid parameters for command 'attach'\n" >&2
                     exit 1
                     ;;
             esac
             shift
         done
-        utils::verbose --msg-color "${CYAN}" "sub_command=attach; modeule=$module" >&2
+        utils::verbose -c "${CYAN}" "sub_command=attach; module=$module\n"
         ;;
     *)
-        echo "Error: Unknown sub-command '$1'" && exit 1
+        utils::ERROR "Unknown sub-command '$1'\n" >&2
+        exit 1
         ;;
 esac
 # Arguments processing end
@@ -312,7 +365,7 @@ case "$sub_command" in
         [[ -n "$app" ]] && cmd_str+=" -app $app"
         ;;
     kill)
-        utils::verbose --force --msg-color "${BGREEN}" --prompt "* " "Running jobs exist:" >&2
+        utils::verbose -f -c "${BGREEN}" -p "* " "Running jobs exist:\n" >&2
 
         # Find existing jobs
         _MODULES=( "${MODULES[@]}" )
@@ -340,7 +393,7 @@ case "$sub_command" in
         done
         _jobs_str="$(tail -n +2 <<< "$_jobs_str")"
 
-        _prompt="$(utils::verbose --force --msg-color "${BGREEN}" --prompt "* " "Type index or job-id to kill: ")"
+        _prompt="$(utils::verbose -f -c "${BGREEN}" -p "* " "Type index or job-id to kill: ")"
         _input=""
         while [[ -z "$_input" ]]; do
             read -r -p "$_prompt" _input
@@ -356,9 +409,14 @@ case "$sub_command" in
                     _job_id="$(awk '{print $1}' <<< "$_target_job")"
                     _module=""
                     for elem in "${_jobs_module_arr[@]}"; do
-                        [[ "$(cut -d ':' -f 1 <<< "$elem")" == "$_job_id" ]] && _module="$(cut -d ':' -f 2 <<< "$elem")"
+                        if [[ "$(cut -d ':' -f 1 <<< "$elem")" == "$_job_id" ]]; then
+                            _module="$(cut -d ':' -f 2 <<< "$elem")"
+                        fi
                     done
-                    [[ -z "$_module" ]] && { echo "Error: Extract job module fail" >&2 ; exit 1; }
+                    if [[ -z "$_module" ]]; then
+                        utils::ERROR "Extract job module fail\n" >&2
+                        exit 1
+                    fi
                     cmd_str="source /global/lsf/cells/${_module}/conf/profile.lsf && bkill $_job_id"
                 fi
             fi
@@ -382,8 +440,9 @@ case "$sub_command" in
         _identifier="${sub_options#*identifier=}"
         _identifier="${_identifier%%:#:*}"
         _identifier="${_identifier%\"*}"
-        cmd_str="$_src_cmd && bsub $sub_options"
+        cmd_str="$_src_cmd && "
         if [[ -z "$interactive_shell" ]]; then
+            cmd_str+="__LSF_JOB_FLAG=1 __LSF_INTERACTIVE_SHELL_FLAG=0 bsub $sub_options"
             if ! grep -q " -o " <<< "$sub_options"; then
                 if [[ ! -d .lsf_logs ]]; then
                     mkdir .lsf_logs
@@ -399,6 +458,7 @@ case "$sub_command" in
             [[ -n "$CITRIX_REMOTE_DISPLAY" ]] && cmd_str+=" export DISPLAY=$CITRIX_REMOTE_DISPLAY\;"
             cmd_str+=" $command"
         else
+            cmd_str+="__LSF_JOB_FLAG=0 __LSF_INTERACTIVE_SHELL_FLAG=1 bsub $sub_options"
             export SHELL=""
             export HOST=""
             export DISPLAY="$CITRIX_REMOTE_DISPLAY"
@@ -412,9 +472,12 @@ case "$sub_command" in
             _input=""
             _hist_int="$(lsf_sh hist "$module" -r | tail -n +2)"
             _job_ids_str="$(tail -n +2 <<< "$_hist_int")"
-            [[ -z "$_job_ids_str" ]] && { echo "Error: No existing interactive shell job" >&2 ; exit 1; }
+            if [[ -z "$_job_ids_str" ]]; then
+                utils::ERROR "No existing interactive shell job\n" >&2
+                exit 1
+            fi
 
-            utils::verbose --force --msg-color "${BGREEN}" --prompt "* " "Running interactive shells exist:" >&2
+            utils::verbose -f -c "${BGREEN}" -p "* " "Running interactive shells exist:\n" >&2
 
             declare -i _i=0
             while read -r line; do
@@ -425,7 +488,7 @@ case "$sub_command" in
                 fi
                 _i+=1
             done <<< "$_hist_int"
-            _prompt="$(utils::verbose --force --msg-color "${BGREEN}" --prompt "* " "Type index or job-id to attach: ")"
+            _prompt="$(utils::verbose -f -c "${BGREEN}" -p "* " "Type index or job-id to attach: ")"
             while [[ -z "$_input" ]]; do
                 read -r -p "$_prompt" _input
                 if [[ -n "$_input" ]]; then
@@ -439,19 +502,22 @@ case "$sub_command" in
                     else
                         _sh="$(awk '{print $3}' <<< "$_target_job")"
                         _job_id="$(awk '{print $1}' <<< "$_target_job")"
-                        cmd_str="$_src_cmd && battach -L $(which "$_sh") $_job_id"
+                        cmd_str="$_src_cmd && "
+                        cmd_str+="__LSF_JOB_FLAG=0 __LSF_INTERACTIVE_SHELL_FLAG=1 "
+                        cmd_str+="battach -L $(which "$_sh") $_job_id"
                     fi
                 fi
             done
         ;;
     *)
-        echo "Error: Unknown sub-command '$1'"
+        utils::ERROR "Unknown sub-command '$1'\n" >&2
         exit 1
         ;;
 esac
 # Construct command string end
-
-utils::verbose --msg-color "${CYAN}" "cmd='$cmd_str'" >&2
-[[ "$dry_run" == false ]] && eval "$cmd_str"
-exec
+utils::verbose -c "${CYAN}" "cmd='$cmd_str'\n"
+if [[ "$dry_run" == false ]]; then
+    eval "$cmd_str"
+    exec
+fi
 
diff --git a/bin/map_depot_path_sh b/bin/map_depot_path_sh
--- a/bin/map_depot_path_sh
+++ b/bin/map_depot_path_sh
@@ -1,25 +1,40 @@
 #!/u/chehuang/bin/bash
-help="Usage: map_depot_path_sh [OPTION]... [PATH]
+help="Usage: map_depot_path_sh [OPTION]... <PATH>
 Help mapping between path and depot path
 options:
-    -m, --mode [MODE]       Specify mode, can be {qa}
+    -d, --depot <P4_PATH>   Specify basic depot path (path before branch)
+                            [Default: //custom/cdesigner]
+                            e.g. //custom/cdesigner/main/dev/... -> //custom/cdesigner
+    -m, --mode <MODE>       Specify mode, can be {qa} [Default: qa]
+                            (Set default to qa because there is only one mode now)
     -v, --verbose           Show verbose messages in console
     -h, --help              Display this help and exit
 "
 
-# shellcheck source-path=SCRIPTDIR
-source "utils_sh"
+source "/u/chehuang/bin/utils_src"
+PATH=/u/chehuang/bin:$PATH
 
 VALID_MODES=("qa")
 
+depot="//custom/cdesigner"
 mode=""
 verbose=false
 path=""
 while [[ $# -gt 0 ]]; do
     case $1 in
+        -d|--depot)
+            shift; depot=$1; shift
+            if [[ ! $depot =~ ^// ]]; then
+                utils::ERROR "Invalid depot path, must start with //\n" >&2
+                exit 1
+            fi
+            ;;
         -m|--mode)
             shift; mode=$1; shift
-            [[ ! ${VALID_MODES[@]} =~ $mode ]] && echo "Error: Invalid mode, valid modes: (${VALID_MODES[@]})"
+            if [[ ! ${VALID_MODES[@]} =~ $mode ]]; then
+                utils::ERROR "Invalid mode, valid modes: (${VALID_MODES[*]})\n" >&2
+                exit 1
+            fi
             ;;
         -v|--verbose)
             verbose=true; shift
@@ -28,67 +43,130 @@ while [[ $# -gt 0 ]]; do
             echo "$help" && exit 0
             ;;
         *)
-            [[ -n $path ]] && { echo "Error: Can't specify multiple paths"; exit 1; }
+            [[ -n $path ]] && { utils::ERROR "Can't specify multiple paths\n" >&2; exit 1; }
             path=$1; shift
             ;;
     esac
 done
 
-utils::verbose --msg-color "${CYAN}" "mode=$mode; verbose=$verbose; path=$path" >&2
+[[ -z $path ]] && { utils::ERROR "Missing path\n" >&2; exit 1; }
 
-if [[ -f $path ]]; then
-    is_file=true
-else
-    is_file=false
-fi
+utils::verbose -c "${CYAN}" "depot=$depot; mode=$mode; verbose=$verbose; path=$path\n"
 
-utils::verbose --msg-color "${BGREEN}" --prompt "* " "is_file: $is_file" >&2
+get_depot_branch_path_of_client_root() {
+    local _depot="$1"
+    local -n _result_ref="$2"
 
+    local _client_spec _view_start_line
+
+    _client_spec="$(p4 client -o)"
+    _view_start_line="$(rg -n "^View:" <<< "$_client_spec" | cut -d ":" -f 1)"
+    # Here assumes that the next 2 folder after the depot path are branch
+    _result_ref="$(
+        sed -n "$((_view_start_line+1)),\$p" <<< "$_client_spec" | \
+        sed -E -n "s|^\\s*($_depot/[^/]+/[^/]+)/.*|\\1|p" | \
+        sort -u
+    )"
+    utils::verbose -c "${BGREEN}" -p "* " "depot_branch_path=$_result_ref\n"
+
+    if [[ $_result_ref =~ $'\n' ]]; then
+        utils::ERROR "Detect multiple candidate depots in view.\n" >&2
+        return 1
+    fi
+
+    return 0
+}
+
+qa_map_depot_path_by_case_path() {
+    local _path="$1"
+    local _depot="$2"
+    local -n _result_ref="$3"
+
+    local _is_file
+    if [[ -f $_path ]]; then
+        _is_file=true
+    else
+        _is_file=false
+    fi
+    utils::verbose -c "${BGREEN}" -p "* " "is_file: $_is_file\n"
+
+    local _dir_name
+    if [[ $_is_file == true ]]; then
+        _dir_name="$(dirname "$_path")"
+    else
+        _dir_name="$_path"
+    fi
+    utils::verbose -c "${BGREEN}" -p "* " "dir_name=$_dir_name\n"
+
+    local _testcase_dir
+    if _testcase_dir="$(dirname "$(readlink -e "$_dir_name/run")")"; then
+        cd "$_testcase_dir" || { utils::ERROR "Failed to cd to $_testcase_dir\n" >&2; return 1; }
+        utils::verbose -c "${BGREEN}" -p "* " "cd $_testcase_dir\n"
+    else
+        utils::ERROR "Invalid path\n" >&2
+        return 1
+    fi
+
+    local _depot_branch_path
+    if ! get_depot_branch_path_of_client_root "$_depot" _depot_branch_path; then
+        return 1
+    fi
+
+    # A strong assumption that qa's testcase path has a trait: <client_root>/sqa/checker/...
+    local _case_relative_path
+    _case_relative_path="$(sed -E 's|.*/(sqa/checker/.*)|\1|' <<< "$_testcase_dir")"
+    utils::verbose -c "${BGREEN}" -p "* " "case_relative_path=$_case_relative_path\n"
+
+    _result_ref="$_depot_branch_path/$_case_relative_path"
+    return 0
+}
+
+qa_map_depot_path_by_case_name() {
+    local _path="$1"
+    local _depot="$2"
+    local -n _result_ref="$3"
+
+    # To allow more modules, contact chehuang
+    local _VALID_MODULES=("primewave_post" "test_suites")
+
+    # case name may contain case mode:
+    #   sae_pwso/test_suites/PrimeWave/stars/P90060183-35839, sae_pwso is the case mode
+    #   test_suites/PrimeWave/stars/P90060183-35839
+    # _pattern looks like: "primewave_post/.+|test_suites/.+"
+    local _pattern="$(tr " " "|" <<< "${_VALID_MODULES[@]/%/\/.+}")"
+    if [[ "$_path" =~ ^($_pattern/.+)$ ]] || [[ "$_path" =~ ^[^/]+/($_pattern/.+)$ ]]; then
+        local _matched_path="${BASH_REMATCH[1]}"
+        utils::verbose -c "${BGREEN}" -p "* " "matched_path=$_matched_path\n"
+    else
+        utils::ERROR "Can't find valid module in path\n" >&2
+        return 1
+    fi
+
+    local _depot_branch_path
+    if ! get_depot_branch_path_of_client_root "$_depot" _depot_branch_path; then
+        return 1
+    fi
+
+    # A strong assumption that qa's testcase path has a trait: <client_root>/sqa/checker/...
+    _result_ref="$_depot_branch_path/sqa/checker/$_matched_path"
+    return 0
+}
+
+depot_path=""
 case $mode in
     qa)
-        PROJECT_BLACKLIST=( "nightly" "nightly_weekend" )
-
-        IFS='/' read -r -a arr <<< "$path"
-        utils::verbose --msg-color "${BGREEN}" --prompt "* " "path=${arr[*]}" >&2
-
-        if [[ "${arr[6]}" == "main" ]]; then
-            branch="${arr[6]}/dev"
-        else
-            branch="${arr[6]%_*}/${arr[6]##*_}"
-        fi
-        utils::verbose --msg-color "${BGREEN}" --prompt "* " "branch=$branch" >&2
-
-        project=${arr[9]}
-        [[ ${PROJECT_BLACKLIST[@]} =~ $project ]] && project=${arr[10]}
-        utils::verbose --msg-color "${BGREEN}" --prompt "* " "project=$project" >&2
-
-        if [[ $is_file == true ]]; then
-            dir_name=${path%/*}
-        else
-            dir_name=$path
-        fi
-
-        testcase_path=$(readlink -e "$dir_name/run") || { echo "Error: Invalid path"; exit 1; }
-
-        remain=""
-        IFS='/' read -r -a arr <<< "$testcase_path"
-        for i in "${!arr[@]}"
-        do
-            if [[ ${arr[$i]} == "checker" ]]; then
-                remain=$(printf "/%s" "${arr[@]:$i}")
-                break
+        if [[ "$path" =~ ^/ ]]; then
+            if ! qa_map_depot_path_by_case_path "$path" "$depot" depot_path; then
+                exit 1
             fi
-        done
-        remain=${remain#/}
-        remain=${remain%/*}
-        utils::verbose --msg-color "${BGREEN}" --prompt "* " "remain=$remain" >&2
-
-        depot_path="//cktsim/qa/$branch/$project/unit_pw/${remain}"
-        if [[ $is_file == true ]]; then
-            depot_path="$depot_path/$(basename "$path")"
+        else
+            if ! qa_map_depot_path_by_case_name "$path" "$depot" depot_path; then
+                exit 1
+            fi
         fi
-        utils::verbose --msg-color "${BGREEN}" --prompt "* " "depot_path=$depot_path" >&2
-
-        echo "$depot_path"
         ;;
 esac
+
+utils::verbose -c "${BGREEN}" -p "* " "depot_path=$depot_path\n"
+[[ -z $depot_path ]] && { utils::ERROR "Map failed\n" >&2; exit 1; }
+echo "$depot_path"
diff --git a/bin/mem_usage_by_user_sh b/bin/mem_usage_by_user_sh
--- a/bin/mem_usage_by_user_sh
+++ b/bin/mem_usage_by_user_sh
@@ -18,8 +18,8 @@ user_1      1.6869      2.096
 user_2      1.887       1.8943
 "
 
-# shellcheck source-path=SCRIPTDIR
-source "utils_sh"
+source "/u/chehuang/bin/utils_src"
+PATH=/u/chehuang/bin:$PATH
 
 sort_col=1
 is_reverse=false
@@ -28,16 +28,19 @@ only_logged=false
 verbose=false
 
 while [[ $# -gt 0 ]]; do
-	case $1 in
-		-c|--column)
+    case $1 in
+        -c|--column)
             if [[ $# -ge 2 ]]; then
                 shift
-                [[ $1 -lt 1 || $1 -gt 3 ]] && { echo "Error: Invalid column, should be 1~3"; exit 1; }
+                if [[ $1 -lt 1 || $1 -gt 3 ]]; then
+                    utils::ERROR "Invalid column, should be 1~3\n" >&2
+                    exit 1
+                fi
                 sort_col=$1; shift
             else
-                echo "-c|--column need an argument" && exit 1
+                utils::ERROR "-c|--column need an argument" >&2 && exit 1
             fi
-			;;
+            ;;
         -r|--reverse)
             is_reverse=true; shift
             ;;
@@ -53,13 +56,14 @@ while [[ $# -gt 0 ]]; do
         -v|--verbose)
             verbose=true; shift
             ;;
-		*)
-            echo "Error: Unknown argument '$1'" && exit 1
-			;;
-	esac
+        *)
+            utils::ERROR "Unknown argument '$1'\n" >&2 && exit 1
+            ;;
+    esac
 done
 
-utils::verbose --msg-color "${CYAN}" "column=$sort_col; reverse=$is_reverse; user=$user; logged=$only_logged" >&2
+utils::verbose -c "${CYAN}" "column=$sort_col; reverse=$is_reverse; user=$user;" \
+    "logged=$only_logged\n"
 
 if [[ "$only_logged" == true ]]; then
     users="$(users | tr ' ' '\n' | sort -u)"
diff --git a/bin/p4_diff_shelves_sh b/bin/p4_diff_shelves_sh
--- a/bin/p4_diff_shelves_sh
+++ b/bin/p4_diff_shelves_sh
@@ -21,9 +21,8 @@ usage:
         p4_diff_shelves_sh -r 2 -f //a.txt 123
 "
 
-# shellcheck source-path=SCRIPTDIR
-source "color_sh"
-source "utils_sh"
+source "/u/chehuang/bin/utils_src"
+PATH=/u/chehuang/bin:$PATH
 
 verbose=false
 rev=""
@@ -53,27 +52,38 @@ while [[ $# -gt 0 ]]; do
             echo "$help" && exit 0
             ;;
         *)
-            [[ -n $change ]] && { echo "Error: Can't specify multiple changes" >&2 ; exit 1; }
+            [[ -n $change ]] && { utils::ERROR "Can't specify multiple changes\n" >&2; exit 1; }
             change="$1"
             ;;
     esac
     shift
 done
 
-[[ -z "$change" ]] && { echo "Error: Missing change" >&2 ; exit 1; }
-[[ -n "$rev" && -z "$file" ]] && { echo "Error: --rev can only be used with --file" >&2 ; exit 1; }
+[[ -z "$change" ]] && { utils::ERROR "Missing change\n" >&2; exit 1; }
+if [[ -n "$rev" && -z "$file" ]]; then
+    utils::ERROR "--rev can only be used with --file\n" >&2
+    exit 1
+fi
 
-utils::verbose --msg-color "${CYAN}" "rev=$rev; file=$file; identical=$is_identical; vscode=$is_vscode; verbose=$verbose; change=$change" >&2
+utils::verbose -c "${CYAN}" "rev=$rev; file=$file; identical=$is_identical;" \
+    "vscode=$is_vscode; verbose=$verbose; change=$change\n"
+
 client_name="$(p4 -z tag -F %clientName% info)"
-[[ "$client_name" == "none" || "$client_name" == "\*unknown\*" ]] && { echo "Error: Missing P4 Client" >&2 ; exit 1; }
+if [[ "$client_name" == "none" || "$client_name" == "\*unknown\*" ]]; then
+    utils::ERROR "Missing P4 Client\n" >&2
+    exit 1
+fi
 
 # Check whether change number match
-[[ -z "$(p4 -z tag -F %change% describe -S -s "$change")" ]] && { echo "Error: Invalid change" >&2 ; exit 1; }
+if [[ -z "$(p4 -z tag -F %change% describe -S -s "$change")" ]]; then
+    utils::ERROR "Invalid change\n" >&2
+    exit 1
+fi
 
 _files=()
 for (( _i=0; 1; ++_i )); do
     if ! _depot_file="$(p4 -z tag -F %depotFile${_i}% describe -S -s "$change")"; then
-        echo "Error: When executing 'p4 -z tag -F %depotFile${_i}% describe -S -s $change'" >&2
+        utils::ERROR "When executing 'p4 -z tag -F %depotFile${_i}% describe -S -s $change'\n" >&2
         exit 1
     fi
 
@@ -82,20 +92,20 @@ for (( _i=0; 1; ++_i )); do
     _files+=("$_depot_file")
 done
 
-utils::verbose --msg-color "${BGREEN}" --prompt "* " "Files:" >&2
+utils::verbose -c "${BGREEN}" -p "* " "Files:\n"
 for f in "${_files[@]}"; do
-    utils::verbose "  $f" >&2
+    utils::verbose "  $f\n"
 done
 
 if [[ -n $file ]]; then
     remote_file="$(p4 -z tag -F %depotFile% where "$file")"
     if [[ ! " ${_files[*]} " =~ [[:space:]]${remote_file}[[:space:]] ]]; then
-        echo "Error: Can't find target file in remote" >&2
+        utils::ERROR "Can't find target file in remote\n" >&2
         exit 1
     fi
     _files=("$remote_file")
-    utils::verbose --msg-color "${BGREEN}" --prompt "* " "Specify only:" >&2
-    utils::verbose "  $remote_file" >&2
+    utils::verbose -c "${BGREEN}" -p "* " "Specify only:\n"
+    utils::verbose "  $remote_file\n"
 fi
 
 regex_add="^[0-9,]+a[0-9,]+$"
@@ -109,23 +119,29 @@ for f in "${_files[@]}"; do
     fi
     if [[ $is_identical == true || $(wc -l <<< "$diff") -ne 1 ]]; then
         if [[ $is_vscode == true ]]; then
-            # Assume the file is //depot/aaa/bbb.txt@=123, save it to $HOME/workdir/.tmp/depot/aaa/bbb.@=123.txt
+            # Assume the file is //depot/aaa/bbb.txt@=123
+            #   save it to $HOME/workdir/.tmp/depot/aaa/bbb.@=123.txt
             # Change the order of ext and '@=xxx' to make vscode could identify the format of file
-     
+
             tmp_folder="$HOME/workdir/.tmp"
             tmp_file_folder="$tmp_folder/$(dirname "${f#//}")"
             mkdir -p "$tmp_file_folder"
-     
+
             tmp_file_name="$(basename "$f")"
             tmp_file_ext="${tmp_file_name##*.}"
             tmp_file_only_name="${tmp_file_name%.*}"
             tmp_file_path="$tmp_file_folder/$tmp_file_only_name.@=$change.$tmp_file_ext"
             p4 print -q "$f@=$change" > "$tmp_file_path"
-     
-            have_str="$(p4 have "$f")" # e.g. //depot/aaa/bbb.txt#5 - /<local workspace path>/aaa/bbb.txt
-            
+
+            # e.g. //depot/aaa/bbb.txt#5 - /<local workspace path>/aaa/bbb.txt
+            have_str="$(p4 have "$f")"
+
             # shellcheck disable=SC2029
-            [[ -z "$__X11_SERVER" ]] && { echo "Error: Env '__X11_SERVER' is not set, please set this env to a host with running code-server" >&2 ; exit 1; }
+            if [[ -z "$__X11_SERVER" ]]; then
+                utils::ERROR "Env '__X11_SERVER' is not set, please set this env to a host" \
+                    "with running code-server\n" >&2
+                exit 1
+            fi
             src_cmd="source \\\$HOME/bin/disguise_vscode_src"
             code_cmd="code -d ${have_str##* - } $tmp_file_path"
             ssh_x11_server_sh "\$HOME/bin/zsh -c \"$src_cmd && $code_cmd\""
diff --git a/bin/sync_case_sh b/bin/sync_case_sh
--- a/bin/sync_case_sh
+++ b/bin/sync_case_sh
@@ -2,17 +2,28 @@
 help="Usage: sync_case_sh [OPTION]... <CASE_PATH>
 Help sync case to client
 options:
+    -d, --depot <P4_PATH>   Specify basic depot path (path before branch)
+                            [Default: //custom/cdesigner]
+                            e.g. //custom/cdesigner/main/dev/... -> //custom/cdesigner
     -v, --verbose           Show verbose messages in console
     -h, --help              Display this help and exit
 "
 
-# shellcheck source-path=SCRIPTDIR
-source "utils_sh"
+source "/u/chehuang/bin/utils_src"
+PATH=/u/chehuang/bin:$PATH
 
 case_path=""
+depot="//custom/cdesigner"
 verbose=false
 while [[ $# -gt 0 ]]; do
     case $1 in
+        -d|--depot)
+            shift; depot=$1; shift
+            if [[ ! $depot =~ ^// ]]; then
+                utils::ERROR "Invalid depot path, must start with //\n" >&2
+                exit 1
+            fi
+            ;;
         -v|--verbose)
             verbose=true; shift
             ;;
@@ -20,30 +31,58 @@ while [[ $# -gt 0 ]]; do
             echo "$help" && exit 0
             ;;
         *)
-            [[ -n $case_path ]] && { echo "Error: Can't specify multiple paths"; exit 1; }
+            if [[ -n $case_path ]]; then
+                utils::ERROR "Can't specify multiple paths\n" >&2
+                exit 1
+            fi
             case_path=$1; shift
             ;;
     esac
 done
 
-utils::verbose --msg-color "${CYAN}" "case_path=$case_path; verbose=$verbose" >&2
+utils::verbose -c "${CYAN}" "depot=$depot; case_path=$case_path; verbose=$verbose\n"
 
-[[ -n "$(command -v map_depot_path_sh)" ]] || { echo "Error: Can't find command 'map_depot_path_sh'" ; exit 1; }
-depot_path=$(map_depot_path_sh -m qa "$case_path") || { echo "Error: Can't find case in depot" ; exit 1; }
-utils::verbose --msg-color "${BGREEN}" --prompt "* " "depot_path=$depot_path" >&2
+if [[ -z "$(command -v map_depot_path_sh)" ]]; then
+    utils::ERROR "Can't find command 'map_depot_path_sh'\n" >&2
+    exit 1
+fi
+if ! depot_path=$(map_depot_path_sh -d "$depot" -m qa "$case_path"); then
+    utils::ERROR "Can't find case in depot\n" >&2
+    exit 1
+fi
+utils::verbose -c "${BGREEN}" -p "* " "depot_path=$depot_path\n"
 
 client_name=$(p4 -z tag -F %clientName% info)
-[[ "$client_name" == "none" ]] && { echo "Error: Missing p4 client name"; exit 1; }
+if [[ "$client_name" == "none" || "$client_name" == "\*unknown\*" ]]; then
+    utils::ERROR "Missing p4 client\n" >&2
+    exit 1
+fi
 
-utils::verbose --msg-color "${BGREEN}" --prompt "* " "client_name=$client_name" >&2
-client_case_path="//${client_name}/qa/${depot_path#*/qa/}"
-utils::verbose --msg-color "${BGREEN}" --prompt "* " "client_case_path=$client_case_path" >&2
+utils::verbose -c "${BGREEN}" -p "* " "client_name=$client_name\n"
+_client_spec="$(p4 client -o)"
+_view_start_line="$(rg -n "^View:" <<< "$_client_spec" | cut -d ":" -f 1)"
+if [[ "$(wc -l <<< "$_view_start_line")" -ne 1 ]]; then
+    utils::ERROR "Client spec should only contains only one 'View:' segment\n" >&2
+    exit 1
+fi
+
+# Here assumes that the next 2 folder after the depot path are branch
+# e.g. //custom/cdesigner/main/dev, depot_path='//custom/cdesigner', branch='main/dev'
+depot_branch_path="$(
+    sed -n "$((_view_start_line+1)),\$p" <<< "$_client_spec" | \
+    sed -E -n "s|^\\s*($depot/[^/]+/[^/]+)/.*|\\1|p" | \
+    sort -u
+)"
+utils::verbose -c "${BGREEN}" -p "* " "depot_branch_path=$depot_branch_path\n"
+
+client_case_path="//${client_name}/${depot_path#"${depot_branch_path}"/}"
+utils::verbose -c "${BGREEN}" -p "* " "client_case_path=$client_case_path\n"
 
 spec_text="\t${depot_path}/... ${client_case_path}/..."
-utils::verbose --msg-color "${BGREEN}" --prompt "* " "spec_text=$spec_text" >&2
+utils::verbose -c "${BGREEN}" -p "* " "spec_text=$spec_text\n"
 
 client_root=$(p4 -z tag -F %clientRoot% info)
-utils::verbose --msg-color "${BGREEN}" --prompt "* " "client_root=$client_root" >&2
+utils::verbose -c "${BGREEN}" -p "* " "client_root=$client_root\n"
 
 client_file="$client_root/.p4client.tmp"
 p4 client -o > "$client_file"
@@ -56,7 +95,7 @@ p4 client -i < "$client_file"
 
 if [[ $is_exists -eq 1 ]]; then
     local_case_path=${client_root}/${client_case_path#//"${client_name}"/}
-    utils::verbose --msg-color "${BGREEN}" --prompt "* " "p4 sync ${client_case_path}/..." >&2
+    utils::verbose -c "${BGREEN}" -p "* " "p4 sync ${client_case_path}/...\n"
     p4 sync "${local_case_path}/..."
 fi
 
diff --git a/bin/synmake_sh b/bin/synmake_sh
--- a/bin/synmake_sh
+++ b/bin/synmake_sh
@@ -1,43 +1,61 @@
 #!/u/chehuang/bin/bash
 
 help="Usage: synmake_sh <OPTION>...
-Supports short keys for usual synmake commands
+Supports short keys for usual synmake commands, only works when run in client root
 options:
     -P, --preset <ENUM>     Use preset enums. They are order irrelevant, and any explicit declared
                             params will override params in preset.
-                            S(simple)='-p S -c <Client Root>/.compile_commands.json -l .synmake.log -t'
-                            A(all)='--always-make' or '-B'
-                            D(debug)='--debug'
+                            S(simple)='-c <Client Root>/.compile_commands.json -l <Client Root>/.synmake.log'
+                            I='--install'
+                            A='--always-make' or '-B'
+                            R='--build-type release'
+                            G='--build-type debug'
+                            D='--build-type develop'
+                            P='--prebuild'
+                            p='--pack'
                             E.G. 'synmake_sh -c test.json -P SA -l test.log' ===
-                                 'synmake_sh -c test.json -l test.log -t -p V -B'
+                                 'synmake_sh -c test.json -l test.log -t -B'
     ---------------------------------------------------------------------------------
-    -d, --debug             Whether use debug build instead of release build
-    -p, --pack <MODE>       Pack packages with specific mode after build success
-                            'S|simple': Only pack primewave tcl
-                            'V|cc_ver': Pack cc version specific files additionally
-                            'A|all': Pack all
+    -m, --module <MODULE>   Specify module, can be {All, PW}
+                            [Default=All]
+    -t, --build-type        Build type
+                            'R|release': Release build
+                            'G|debug': Debug build
+                            'D|develop': Develop build [Default]
+    -P, --prebuild          Run prebuild before build (only for cc)
+    -i, --install           Build
+    -p, --pack              Pack packages after build success
     -B, --always-make       Unconditionally make all targets
     -c, --compdb <FILE>     Output compdb file name
     -l, --log <FILE>        Output log file name
-    -t, --tail              Whether tail log file after build success. The line 
-                            number is auto detected
+    -s, --summary           Whether output summary of log file after build success
     --dry-run               Only show the constructed command instead of running it
     -v, --verbose           Show verbose messages in console
     -h, --help              Display this help and exit
 "
 
-# shellcheck source-path=SCRIPTDIR
-source "utils_sh"
+source "/u/chehuang/bin/utils_src"
+PATH=/u/chehuang/bin:$PATH
+
+MODULES=("All" "PW")
 
 preset=""
-debug=false
-pack=""
+module="All"
+build_type=""
+prebuild=false
+install=false
+pack=false
 always_make=false
 compdb=""
 log_file=""
-is_tail=false
+is_summary=false
 dry_run=false
 verbose=false
+
+if [[ "$(pwd)" != $(p4 -z tag -F %clientRoot% info) ]]; then
+    utils::ERROR "synmake_sh can only run in client root\n" >&2
+    exit 1
+fi
 
 original_args=( "$@" )
 while [[ $# -gt 0 ]]; do
@@ -54,24 +72,34 @@ done
 
 while read -rn 1 ch; do
     case $ch in
-        S|s)
-            # Fallback to absolute path if relative path starts with multiple "../"
-            _client_root="$(p4 -z tag -F %clientRoot% info)"
-            _pwd="$(pwd)"
-            _relative_path="$(realpath --relative-to "$_pwd" "$_client_root")"
-            [[ "$_relative_path" =~ \.\./\.\. ]] || _client_root="$_relative_path"
-            compdb="$_client_root/.compile_commands.json"
+        S)
+            compdb=".compile_commands.json"
             log_file=".synmake.log"
-            is_tail=true
+            is_summary=true
             ;;
-        A|a)
+        I)
+            install=true
+            ;;
+        A)
             always_make=true
             ;;
-        D|d)
-            debug=true
+        R)
+            build_type=release
+            ;;
+        G)
+            build_type=debug
+            ;;
+        D)
+            build_type=develop
+            ;;
+        P)
+            prebuild=true
+            ;;
+        p)
+            pack=true
             ;;
         *)
-            echo "Error: Invalid preset '$ch'"
+            utils::ERROR "Invalid preset '$ch'\n" >&2
             exit 1
             ;;
     esac
@@ -83,23 +111,61 @@ while [[ $# -gt 0 ]]; do
         -P|--preset)
             shift; shift
             ;;
-        -d|--debug)
-            debug=true; shift
+        -m|--module)
+            shift
+            # shellcheck disable=SC2076
+            if [[ ! " ${MODULES[@]} " =~ " $1 " ]]; then
+                utils::ERROR "Invalid module, valid modules: (${MODULES[*]})\n" >&2
+                exit 1
+            fi
+            module=$1
+            shift
+            ;;
+        -t|--build-type)
+            shift
+            case "$1" in
+                R|release|G|debug|D|develop)
+                    ;;
+                *)
+                    utils::ERROR "Invalid build type '$1'\n" >&2
+                    exit 1
+                    ;;
+            esac
+            build_type=$1
+            shift
+            ;;
+        -b|--prebuild)
+            prebuild=true; shift
+            ;;
+        -i|--install)
+            install=true; shift
             ;;
         -p|--pack)
-            shift; pack=$1; shift
+            pack=true; shift
             ;;
         -B|--always-make)
             always_make=true; shift
             ;;
         -c|--compdb)
-            shift; compdb=$1; shift
+            shift
+            if [[ -e "$1" && ! -f "$1" ]]; then
+                utils::ERROR "compdb exists and is not a file\n" >&2
+                exit 1
+            fi
+            compdb=$1
+            shift
             ;;
         -l|--log)
-            shift; log_file=$1; shift
+            shift
+            if [[ -e "$1" && ! -f "$1" ]]; then
+                utils::ERROR "log-file exists and is not a file\n" >&2
+                exit 1
+            fi
+            log_file=$1
+            shift
             ;;
-        -t|--tail)
-            is_tail=true; shift
+        -s|--summary)
+            is_summary=true; shift
             ;;
         --dry-run)
             dry_run=true; shift
@@ -111,175 +177,175 @@ while [[ $# -gt 0 ]]; do
             echo "$help" && exit 0
             ;;
         *)
-            echo "Error: Unknow parameter '$1'"
+            utils::ERROR "Unknown parameter '$1'\n" >&2
             exit 1
             ;;
     esac
 done
 
-utils::verbose --msg-color "${CYAN}" "debug=$debug; pack=$pack; always-make=$always_make; compdb=$compdb; log=$log_file; tail=$is_tail" >&2
+if [[ "$module" != "All" ]]; then
+    compdb=""
+    utils::verbose -c "${BRED}" -p "* " "Ignore parameter '-compdb' because it only build specific" \
+        "module\n"
+fi
+
+case "$build_type" in
+    R|release)
+        build_type="r"
+        ;;
+    G|debug)
+        build_type="g"
+        compdb=""
+        utils::verbose -c "${BRED}" -p "* " \
+            "Ignore parameter '-compdb' because it's a debug build\n"
+        ;;
+    ""|D|develop)
+        build_type="d"
+        ;;
+esac
+[[ -n "$log_file" ]] && log_file="${log_file%.*}.${build_type}.${log_file##*.}"
+
+utils::verbose -c "${CYAN}" \
+    "module=$module; build-type=$build_type; prebuild=$prebuild; install=$install; pack=$pack; " \
+    "always-make=$always_make; compdb=$compdb; log=$log_file; summary=$is_summary\n"
 
 client_name="$(p4 -z tag -F %clientName% info)"
-[[ "$client_name" == "none" || "$client_name" == "\*unknown\*" ]] && { echo "Error: Missing P4 Client"; exit 1; }
+if [[ "$client_name" == "none" || "$client_name" == "\*unknown\*" ]]; then
+    utils::ERROR "Missing P4 Client\n" >&2
+    exit 1
+fi
+
+client_root="$(p4 -z tag -F %clientRoot% info)"
 
 #--------------------
-# build command
-build_cmd=""
+# prebuild
+prebuild_cmd=""
+if [[ "$prebuild" == true ]]; then
+    if [[ "$module" != "PW" ]]; then
+        if [[ -n "$log_file" ]]; then
+            prebuild_cmd=" -log \"${log_file%.*}.prebuild.${log_file##*.}\""
+        fi
+        prebuild_cmd="synmake$prebuild_cmd prebuild"
 
-if [[ "$always_make" == true ]]; then
-    build_cmd="$build_cmd -B"
-fi
-
-if [[ -n "$compdb" ]]; then
-    build_cmd="$build_cmd -compdb \"$compdb\""
-fi
-
-if [[ -n "$log_file" ]]; then
-    build_cmd="$build_cmd -log \"$log_file\""
-fi
-
-if [[ -n "$build_cmd" || "$is_tail" == true ]]; then
-    if [[ "$debug" == false ]]; then
-        build_cmd="synmake$build_cmd install"
+        utils::verbose -f -c "${BGREEN}" -p "* " "Prebuilding ...\n"
+        utils::verbose "  $prebuild_cmd\n"
+        if [[ "$dry_run" == false ]]; then
+            if bash -c "$prebuild_cmd"; then
+                utils::verbose -f -c "${CYAN}" "  [$(date +"%Y-%m-%d %H:%M:%S")]\n"
+            else
+                utils::ERROR "Prebuild fail\n" >&2
+                exit 1
+            fi
+        fi
     else
-        build_cmd="synmake$build_cmd install-g"
+        utils::WARNING "Can't apply prebuild to module 'PW', ignore\n" >&2
+    fi
+fi
+
+#--------------------
+# build
+build_cmd=""
+build_status=0
+
+if [[ "$install" == true ]]; then
+    build_options=""
+    if [[ "$module" == "PW" ]]; then
+        [[ ! -d primewave ]] && { utils::ERROR "Missing 'primewave' folder\n" >&2; exit 1; }
+        build_options+=" -C primewave"
     fi
 
-    utils::verbose --msg-color "${BGREEN}" --prompt "* " "build command:" >&2
-    utils::verbose "  $build_cmd" >&2
+    if [[ "$always_make" == true ]]; then
+        build_options+=" -B"
+    fi
+
+    if [[ -n "$compdb" ]]; then
+        build_options+=" -compdb \"$(utils::get_relative_path -d 2 "$(pwd)" "$compdb")\""
+    fi
+
+    if [[ -n "$log_file" ]]; then
+        build_options+=" -log \"$(utils::get_relative_path -d 2 "$(pwd)" "$log_file")\""
+    fi
+
+    build_cmd+="synmake$build_options install"
+    case "$build_type" in
+        g|d)
+            build_cmd+="-$build_type"
+            ;;
+    esac
+
+    utils::verbose -f -c "${BGREEN}" -p "* " "Building ...\n"
+    utils::verbose "  $build_cmd\n"
+    if [[ "$dry_run" == false ]]; then
+        bash -c "$build_cmd"
+        build_status=$?
+
+        # Overwrite compile_commands.json if it's fully build
+        status_code=$?
+        if [[ "$always_make" == true && "$status_code" == 0 ]] ; then
+            if [[ "$build_type" != "g" ]]; then
+                [[ -n "$compdb" && -e "$compdb" ]] && cp "$compdb" "$client_root/compile_commands.json"
+                # Our make file set some of compile variable with escape on double quote which is
+                #   meaningless and make clangd can't parse macro 'ASSERT_RETURN' correctly
+                # Here replace \\\"VALUE\\\" to \"VALUE\"
+                sed -i 's|\\\\\\"|\\"|g' "$client_root/compile_commands.json"
+            fi
+        fi
+
+        # Remove .smk_compdb_* because it makes next synmake run generate weird error messages
+        rm "$client_root/.smk_compdb_"* 2> /dev/null
+
+        utils::verbose -f -c "${CYAN}" "  [$(date +"%Y-%m-%d %H:%M:%S")]\n"
+    fi
 fi
+
+#--------------------
+# tail
+if [[ -n "$build_cmd" && -n "$log_file" && "$is_summary" == true ]]; then
+    utils::verbose -f -c "${BGREEN}" -p "* " "$log_file:\n"
+    utils::verbose "  tail -n +<Auto Detect> $log_file\n"
+    if [[ "$dry_run" == false ]]; then
+        if [[ "$build_status" -eq 0 ]]; then
+            tail -n +"$(rg --case-sensitive --line-number "List of" "$log_file" | cut -d ':' -f 1)" "$log_file"
+        else
+            tail -n 250 "$log_file" | rg -B 1 -M 0 -i "(^| )error"; tail -n 2 "$log_file"
+        fi
+    fi
+fi
+[[ "$build_status" -eq 0 ]] || exit 1
 
 #--------------------
 # pack command
 pack_cmd=""
-pack_verbose_cmd=""
-
-v_seperator="echo \"--------------------\"
-"
-
-if [[ -n "$pack" ]]; then
-    utils::verbose --msg-color "${BGREEN}" --prompt "* " "pack command:" >&2
-    if [[ "$debug" == true ]]; then
-        pack_cmd="$v_seperator    synmake dbgpack"
-        pack_verbose_cmd="synmake dbgpack"
-    else
-        pack_cmd="$v_seperator    synmake optpack"
-        pack_verbose_cmd="synmake optpack"
+if [[ "$pack" == true ]]; then
+    utils::verbose -f -c "${BGREEN}" -p "* " "Packing ...\n"
+    pack_cmd="synmake -C primewave"
+    if [[ -n "$log_file" ]]; then
+        _log_file="$(utils::get_relative_path -d 2 "$(pwd)/primewave" "$log_file")"
+        pack_cmd+=" -log \"${_log_file%.*}.pack.${_log_file##*.}\""
     fi
-    case "$pack" in
-        S|s|simple)
-            pack_cmd="${pack_cmd}-simple"
-            pack_verbose_cmd="${pack_verbose_cmd}-S"
+
+    case "$build_type" in
+        r)
+            pack_cmd+=" optpack"
             ;;
-        V|v|cc_ver)
-            pack_cmd="${pack_cmd}-cc_ver"
-            pack_verbose_cmd="${pack_verbose_cmd}-V"
+        g)
+            pack_cmd+=" dbgpack"
             ;;
-        A|a|all)
+        d)
+            pack_cmd+=" devpack"
             ;;
-        *)
-            echo "Error: Invalid pack category '$pack'"
-            exit 1
     esac
-    utils::verbose "  $pack_verbose_cmd" >&2
-fi
 
-#--------------------
-# tail command
-success_tail_cmd=""
-success_tail_verbose_cmd=""
-fail_tail_cmd=""
-fail_tail_verbose_cmd=""
-
-v_seperator="echo \"--------------------\"
-    utils::verbose --msg-color \"\${BGREEN}\" --prompt \"* \" \"$log_file:\"
-"
-
-if [[ -n "$log_file" && "$is_tail" == true ]]; then
-    utils::verbose --msg-color "${BGREEN}" --prompt "* " "success tail command:" >&2
-
-    auto_detect_cmd="\$(rg --case-sensitive --line-number \"List of\" $log_file | cut -d ':' -f 1)"
-
-    success_tail_cmd="$v_seperator    tail -n +$auto_detect_cmd $log_file"
-    success_tail_verbose_cmd="tail -n +<Auto Detect> $log_file"
-
-    utils::verbose "  $success_tail_verbose_cmd" >&2
-fi
-
-if [[ -n "$log_file" ]]; then
-    utils::verbose --msg-color "${BGREEN}" --prompt "* " "fail tail command:" >&2
-
-    fail_tail_cmd="$v_seperator    tail -n 250 $log_file | rg -B 1 -M 0 -i \"(^| )error\"; tail -n 2 $log_file"
-    fail_tail_verbose_cmd="tail -n 250 $log_file | rg -B 1 -M 0 -i \"(^| )error\"; tail -n 2 $log_file"
-
-    utils::verbose "  $fail_tail_verbose_cmd" >&2
-fi
-
-#--------------------
-# final command
-nl=$'\n'
-final_cmd=""
-verbose_cmd=""
-if [[ -n "$build_cmd" ]]; then
-    final_cmd="$build_cmd"
-    final_cmd="$final_cmd${nl}status=\$?"
-    final_cmd="$final_cmd${nl}if [[ \$status -eq 0 ]] ; then"
-    [[ -n "$success_tail_cmd" ]] && final_cmd="$final_cmd${nl}    $success_tail_cmd"
-    if [[ -n "$pack_cmd" ]]; then
-        final_cmd="$final_cmd${nl}    $pack_cmd"
-    else
-        final_cmd="$final_cmd${nl}    exit \$status"
-    fi
-    final_cmd="$final_cmd${nl}else"
-    [[ -n "$fail_tail_cmd" ]] && final_cmd="$final_cmd${nl}    $fail_tail_cmd"
-    final_cmd="$final_cmd${nl}    exit \$status"
-    final_cmd="$final_cmd${nl}fi"
-
-    verbose_cmd="$build_cmd"
-    verbose_cmd="$verbose_cmd${nl}  status=\$?"
-    verbose_cmd="$verbose_cmd${nl}  if [[ \$status -eq 0 ]] ; then"
-    [[ -n "$success_tail_verbose_cmd" ]] && verbose_cmd="$verbose_cmd${nl}      $success_tail_verbose_cmd"
-    if [[ -n "$pack_verbose_cmd" ]]; then
-        verbose_cmd="$verbose_cmd${nl}      $pack_verbose_cmd"
-    else
-        verbose_cmd="$verbose_cmd${nl}      exit \$status"
-    fi
-    verbose_cmd="$verbose_cmd${nl}  else"
-    [[ -n "$fail_tail_verbose_cmd" ]] && verbose_cmd="$verbose_cmd${nl}      $fail_tail_verbose_cmd"
-    verbose_cmd="$verbose_cmd${nl}      exit \$status"
-    verbose_cmd="$verbose_cmd${nl}  fi"
-else
-    final_cmd="$pack_cmd"
-    verbose_cmd="  $pack_verbose_cmd"
-fi
-
-utils::verbose --msg-color "${BGREEN}" --prompt "* " "final_cmd:" >&2
-utils::verbose "  $verbose_cmd" >&2
-utils::verbose -- "--------------------" >&2
-
-if [[ "$dry_run" == true ]]; then
-    exit 0
-fi
-
-_client_root="$(p4 -z tag -F %clientRoot% info)"
-
-eval "$final_cmd"
-
-# Overwrite compile_commands.json if it's fully build
-exit_code=$?
-if [[ "$always_make" == true && "$exit_code" == 0 ]] ; then
-    if [[ "$debug" == true ]]; then
-        echo "Skip backup .compile_commands.json because it's a debug build" >&2
-    else
-        f="$_client_root/.compile_commands.json"
-        [[ -e "$f" ]] && cp "$f" "$_client_root/compile_commands.json"
-        # Our make file set someof compile variable with escape on double quote which is meaningless
-        #   and make clangd can't parse macro 'ASSERT_RETURN' correctly
-        # Here replace \\\"VALUE\\\" to \"VALUE\"
-        sed -i 's|\\\\\\"|\\"|g' "$_client_root/compile_commands.json"
+    utils::verbose "  $pack_cmd\n"
+    if [[ "$dry_run" == false ]]; then
+        if bash -c "$pack_cmd"; then
+            utils::verbose -f -c "${CYAN}" "  [$(date +"%Y-%m-%d %H:%M:%S")]\n"
+        else
+            utils::ERROR "Pack fail\n" >&2
+            exit 1
+        fi
     fi
 fi
 
-# Remove .smk_compdb_* because it makes next synmake run generate weird error messages
-rm "$_client_root/.smk_compdb_"* 2> /dev/null
+exit 0
 
diff --git a/bin/ude_sh b/bin/ude_sh
--- a/bin/ude_sh
+++ b/bin/ude_sh
@@ -1,15 +1,44 @@
 #!/u/chehuang/bin/bash
+
+help="Usage: ude_sh <ROOT> [<Args for ude3>...]
+Help to initialize and run ude cases with specific settings in <ROOT>
+    e.g. ude_sh . -- --command \"source /remote/cad-rep/msip/ude_conf/CSO/run.tcl\"
+"
+
+[[ "$1" == "-h" || "$1" == "--help" ]] && { echo "$help"; exit 0; }
+
+source "/u/chehuang/bin/utils_src"
+PATH=/u/chehuang/bin:$PATH
+
 source /remote/cad-rep/etc/.bashrc
 module load ude-wrapper
 
 export OSTYPE=linux
 export P4PORT=p4p-us01:1999
+unset XDG_RUNTIME_DIR
 
 root_dir="$(realpath "$1")"
+shift
+
 source_file="$root_dir/source_me"
+
+if [[ ! -e "$HOME/cd_lib" ]]; then
+    utils::ERROR "$HOME/cd_lib does not exist\n" >&2
+    exit 1
+fi
+if [[ ! -L "$HOME/cd_lib" ]]; then
+    utils::ERROR "$HOME/cd_lib is not a link, link this to your work directory to prevent ude" \
+        "cases occupy too much space in your home directory" >&2
+fi
 
 #original_source_file="/remote/cad-rep/msip/ude_conf/CSO/sourceme"
 global_source_file="$HOME/cd_lib/source_me"
+if [[ ! -e "$global_source_file" ]]; then
+    echo "cp /remote/cad-rep/msip/ude_conf/CSO/sourceme $global_source_file" >&2
+    cp "/remote/cad-rep/msip/ude_conf/CSO/sourceme" "$global_source_file"
+    echo "Any further project will use $global_source_file as default source file" >&2
+fi
+
 if [[ ! -f "$source_file" ]]; then
     echo "cp $global_source_file $source_file" >&2
     cp "$global_source_file" "$source_file"
@@ -22,33 +51,48 @@ if [[ ! -d "$custom_dir" ]]; then
 fi
 if ! grep -q -E "^setenv SYNOPSYS_CUSTOM_LOCAL .+" "$source_file"; then
     echo "append \"setenv SYNOPSYS_CUSTOM_LOCAL $custom_dir\" to $source_file" >&2
-    echo "setenv SYNOPSYS_CUSTOM_LOCAL $custom_dir" >> "$source_file"
+    printf "setenv SYNOPSYS_CUSTOM_LOCAL %s\n\n" "$custom_dir" >> "$source_file"
 fi
 
 echo "Running ude..." >&2
 ude_log_file="$root_dir/.ude.log"
-ude3 -s "$source_file" --command "source /remote/cad-rep/msip/ude_conf/CSO/run.tcl" > "$ude_log_file" 2>&1
+# It's normal if the message below does not quote arguments with spaces, use 'set -x' instead
+# echo " * ude3 -s \"$source_file\" $* > \"$ude_log_file\" 2>&1" >&2
+ude3 -s "$source_file" "$@" > "$ude_log_file" 2>&1
 
-grep -q "error status" <<< "$(tail -n 1 "$ude_log_file")" && { echo "Error: Fail to launch ude, refer to log file for detailed message" >&2 ; exit 1; }
+if grep -q "error status" <<< "$(tail -n 1 "$ude_log_file")"; then
+    utils::ERROR "Fail to launch ude, refer to log file for detailed message\n" >&2
+    exit 1
+fi
 
-[[ -z "$(command -v validate_link_sh)" ]] && { echo "Error: Missing validate_link_sh, get this script from /u/chehuang/bin" >&2 ; exit 1; }
+if [[ -z "$(command -v validate_link_sh)" ]]; then
+    utils::ERROR "Missing validate_link_sh, get this script from /u/chehuang/bin\n" >&2
+    exit 1
+fi
 
-case_folder="$(dirname "$(rg "^$HOME/cd_lib/.+/.cdesigner.tcl = \w+$" "$ude_log_file" | cut -d " " -f 1)")"
+rg_result="$(rg "^$HOME/cd_lib/.+/.cdesigner.tcl = \w+$" "$ude_log_file")"
+first_field="$(echo "$rg_result" | cut -d " " -f 1)"
+case_folder="$(dirname "$first_field")"
 
 lib_def_path="$root_dir/lib.defs"
 case_lib_def_path="$case_folder/lib.defs"
+if [[ ! -e "$case_lib_def_path" || ! -f "$case_lib_def_path" ]]; then
+    utils::ERROR "Invalid case folder ($case_folder)\n" >&2
+    exit 1
+fi
+
 if ! validate_link_sh "$lib_def_path" || [[ "$(readlink "$lib_def_path")" != "$case_lib_def_path" ]]; then
     echo "ln -sf \"$case_lib_def_path\" \"$lib_def_path\"" >&2
     ln -sf "$case_lib_def_path" "$lib_def_path"
 fi
 
 sim_folder="$root_dir/simulation"
+case_sim_folder="$case_folder/simulation"
 if [[ ! -d "$sim_folder" ]]; then
     echo "mkdir \"$sim_folder\"" >&2
     mkdir "$sim_folder"
 fi
-case_sim_folder="$case_folder/simulation"
-if [[ ! -e "$case_sim_folder" || -L "$case_sim_folder" ]]; then
+if ! validate_link_sh "$case_sim_folder" || [[ "$(readlink "$case_sim_folder")" != "$sim_folder" ]]; then
     echo "ln -sf \"$sim_folder\" \"$case_sim_folder\"" >&2
     ln -sf "$sim_folder" "$case_sim_folder"
 fi
